travis:
  secure:
    BINSTAR_TOKEN: Vi539wWvRW456pfzkaqvh+MAQEDjNYM36LtQ/j54UZERz6RiIFhuUjrW7DdS5+7EMI6a4I+rAXvT0kpWUytf5mNZnK7U1rc2v197Z8xQfSuccC4UfRjP5aHkucY3BLF73caO/EwYskISYdyunbbP6CIZkH3EMLr+j2UKeMfVZ6xnA1nG3/aG/wYdcmYtgV1SWPuIs3lfgccOMP71T95ivYhVB9Reen8H8KUq6LFYmADsrYIms4af22C32sHdwd3HYN2XtlpNbRzooK0SmRYLj5dpQti64QPwVznkGgkwzmjuYLWuCNHiaLXvtmtlwxunm1bViYhv5Vro3qa4Or7DTp8S0oznvfxWQkrs5kwk1RHotkinJ7n5b9BrsP8gWfuUnVIJLk/ArYJiLrjpx5TweHWZmBCIw0clZRMm9RT74BJOFEFoVDBRK7g6ALyjMOti+UohPAZ2lmRSE1IG82W2TUBc6fbmdgR3kWXYbwr5Ob+gE1oYd+GodgqEZnHFptdhauo7Z86LhVU3cgcv2RTHwuswL4zzWNIqny4uXJkwGsSfe4F8FTRGygtPZ8uImiSwgQOXPJ35yGD3lV8J1BkNvwSJTp7jwZeeryAxnd9z78ZhNlKCqvwlRLPORwN4pgatWDnjxHLsTPMgL2S3vlWK93QoR71iRX0I03Lpyo8GLXE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
